repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.100.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terragrunt_fmt
      - id: terragrunt_validate_inputs
        files: (/terragrunt\.hcl)$
      - id: terragrunt_validate
        files: (/terragrunt\.hcl)$
        args:
          - --hook-config=--tf-path=tofu
      # - id: terraform_trivy
      # - id: infracost_breakdown
